package com.paylogic.humora.core.security

import android.content.Context
import android.location.Location
import android.os.Build
import android.provider.Settings
import java.io.File

data class AntiSpoofResult(
    val isSecure: Boolean,
    val failureReason: String? = null
)

object AntiSpoofEngine {

    /**
     * Validates that the device location is authentic and not generated by a fake GPS app.
     */
    fun validateLocation(location: Location?, context: Context): AntiSpoofResult {
        if (location == null) {
            return AntiSpoofResult(false, "GPS signal unavailable")
        }

        // 1. Android API level Mock Location Flag
        val isMock = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            location.isMock
        } else {
            @Suppress("DEPRECATION")
            location.isFromMockProvider
        }

        if (isMock) {
            return AntiSpoofResult(false, "Fake/Mock GPS detected. Please disable spoofing apps.")
        }

        // 2. Check if developer options / mock app setting is engaged (pre-Android 6 or enabled app)
        try {
            val mockAppSetting = Settings.Secure.getString(
                context.contentResolver,
                "mock_location"
            )
            if (mockAppSetting != null && mockAppSetting != "0") {
                return AntiSpoofResult(false, "Mock location setting is active.")
            }
        } catch (_: Exception) {
            // Ignore if permission restricted
        }

        return AntiSpoofResult(true)
    }

    /**
     * Checks if the device has root binaries that could intercept GPS calls.
     */
    fun isDeviceRooted(): Boolean {
        val rootPaths = arrayOf(
            "/system/app/Superuser.apk",
            "/sbin/su",
            "/system/bin/su",
            "/system/xbin/su",
            "/data/local/xbin/su",
            "/data/local/bin/su",
            "/system/sd/xbin/su",
            "/system/bin/failsafe/su",
            "/data/local/su"
        )
        return rootPaths.any { path ->
            try {
                File(path).exists()
            } catch (_: Exception) {
                false
            }
        }
    }
}
